### ISSUE TITLE
GSSAPI Error

### ISSUE THREAD

**Issue by ambalabanov** [ambalabanov/lukscrow#1]
```python
./lukscrow --luks-device /dev/sda6 --ldap-url "ldap://dc.domain.local" --computers-base-dn "CN=Computers,DC=domain,DC=local" --unlock-key ********
Using Kerberos credential cache /tmp/tmpe1rn7bjx
Traceback (most recent call last):
  File "/root/lukscrow/./lukscrow", line 222, in <module>
    main()
  File "/root/lukscrow/./lukscrow", line 196, in main
    con = connect_ad(args.ldap_url)
  File "/root/lukscrow/./lukscrow", line 71, in connect_ad
    con.sasl_interactive_bind_s('', auth_tokens)
  File "/root/.pyenv/versions/3.9.1/envs/lukscrow-env/lib/python3.9/site-packages/ldap/ldapobject.py", line 476, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_flags)
  File "/root/.pyenv/versions/3.9.1/envs/lukscrow-env/lib/python3.9/site-packages/ldap/ldapobject.py", line 340, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/root/.pyenv/versions/3.9.1/envs/lukscrow-env/lib/python3.9/site-packages/ldap/compat.py", line 46, in reraise
    raise exc_value
  File "/root/.pyenv/versions/3.9.1/envs/lukscrow-env/lib/python3.9/site-packages/ldap/ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
ldap.LOCAL_ERROR: {'result': -2, 'desc': 'Local error', 'ctrls': [], 'info': 'SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database)'}


```

**Comment by ambalabanov** [comment]
```
# KRB5_TRACE=/dev/stderr ldapsearch -Y GSSAPI -H ldap://dc.domain.local -s base ""
SASL/GSSAPI authentication started
ldap_sasl_interactive_bind_s: Local error (-2)
	additional info: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database)
854: Getting credentials andrey@DOMAIN.LOCAL -> ldap/192.168.88.99@ using ccache FILE:/tmp/krb5cc_143201001_9q7SvZ
[12648] 1612939388.390855: Retrieving andrey@DOMAIN.LOCAL -> ldap/192.168.88.99@ from FILE:/tmp/krb5cc_143201001_9q7SvZ with result: -1765328243/Matching credential not found (filename: /tmp/krb5cc_143201001_9q7SvZ)
[12648] 1612939388.390856: Retrying andrey@DOMAIN.LOCAL -> ldap/192.168.88.99@DOMAIN.LOCAL with result: -1765328243/Matching credential not found (filename: /tmp/krb5cc_143201001_9q7SvZ)
[12648] 1612939388.390857: Server has referral realm; starting with ldap/192.168.88.99@DOMAIN.LOCAL
[12648] 1612939388.390858: Retrieving andrey@DOMAIN.LOCAL -> krbtgt/DOMAIN.LOCAL@DOMAIN.LOCAL from FILE:/tmp/krb5cc_143201001_9q7SvZ with result: 0/Success
[12648] 1612939388.390859: Starting with TGT for client realm: andrey@DOMAIN.LOCAL -> krbtgt/DOMAIN.LOCAL@DOMAIN.LOCAL
[12648] 1612939388.390860: Requesting tickets for ldap/192.168.88.99@DOMAIN.LOCAL, referrals on
[12648] 1612939388.390861: Generated subkey for TGS request: aes256-cts/B928
[12648] 1612939388.390862: etypes requested in TGS request: aes256-cts, aes128-cts, aes256-sha2, aes128-sha2, des3-cbc-sha1, rc4-hmac, camellia128-cts, camellia256-cts
[12648] 1612939388.390864: Encoding request body and padata into FAST request
[12648] 1612939388.390865: Sending request (1623 bytes) to DOMAIN.LOCAL
[12648] 1612939388.390866: Initiating TCP connection to stream 192.168.88.99:88
[12648] 1612939388.390867: Sending TCP request to stream 192.168.88.99:88
[12648] 1612939388.390868: Received answer (319 bytes) from stream 192.168.88.99:88
[12648] 1612939388.390869: Terminating TCP connection to stream 192.168.88.99:88
[12648] 1612939388.390870: Response was from master KDC
[12648] 1612939388.390871: Decoding FAST response
[12648] 1612939388.390872: TGS request result: -1765328377/Server not found in Kerberos database
[12648] 1612939388.390873: Requesting tickets for ldap/192.168.88.99@DOMAIN.LOCAL, referrals off
[12648] 1612939388.390874: Generated subkey for TGS request: aes256-cts/BC7C
[12648] 1612939388.390875: etypes requested in TGS request: aes256-cts, aes128-cts, aes256-sha2, aes128-sha2, des3-cbc-sha1, rc4-hmac, camellia128-cts, camellia256-cts
[12648] 1612939388.390877: Encoding request body and padata into FAST request
[12648] 1612939388.390878: Sending request (1623 bytes) to DOMAIN.LOCAL
[12648] 1612939388.390879: Initiating TCP connection to stream 192.168.88.99:88
[12648] 1612939388.390880: Sending TCP request to stream 192.168.88.99:88
[12648] 1612939388.390881: Received answer (319 bytes) from stream 192.168.88.99:88
[12648] 1612939388.390882: Terminating TCP connection to stream 192.168.88.99:88
[12648] 1612939388.390883: Response was from master KDC
[12648] 1612939388.390884: Decoding FAST response
[12648] 1612939388.390885: TGS request result: -1765328377/Server not found in Kerberos database
```

**Comment by ambalabanov** [comment]
```
# KRB5_TRACE=/dev/stderr ./lukscrow --luks-device /dev/sda6 --ldap-url "ldap://dc.domain.local" --computers-base-dn "CN=Computers,DC=domain,DC=local" --unlock-key ********
[15063] 1612941480.177400: Getting initial credentials for UBUNTU20$@DOMAIN.LOCAL
[15063] 1612941480.177401: Looked up etypes in keytab: rc4-hmac, aes128-cts, aes256-cts
[15063] 1612941480.177403: Sending unauthenticated request
[15063] 1612941480.177404: Sending request (189 bytes) to DOMAIN.LOCAL
[15063] 1612941480.177405: Sending initial UDP request to dgram 192.168.88.99:88
[15063] 1612941480.177406: Received answer (205 bytes) from dgram 192.168.88.99:88
[15063] 1612941480.177407: Response was from master KDC
[15063] 1612941480.177408: Received error from KDC: -1765328359/Additional pre-authentication required
[15063] 1612941480.177411: Preauthenticating using KDC method data
[15063] 1612941480.177412: Processing preauth types: PA-PK-AS-REQ (16), PA-PK-AS-REP_OLD (15), PA-ETYPE-INFO2 (19), PA-ENC-TIMESTAMP (2)
[15063] 1612941480.177413: Selected etype info: etype aes256-cts, salt "DOMAIN.LOCALhostubuntu20.domain.local", params ""
[15063] 1612941480.177414: Retrieving UBUNTU20$@DOMAIN.LOCAL from FILE:/etc/krb5.keytab (vno 0, enctype aes256-cts) with result: 0/Success
[15063] 1612941480.177415: AS key obtained for encrypted timestamp: aes256-cts/9559
[15063] 1612941480.177417: Encrypted timestamp (for 1612941480.186428): plain 301AA011180F32303231303231303037313830305AA105020302D83C, encrypted 470B8F0101F03EDFC8AC90D89DF5EB6D5A53C69FEF00001454E829D1B2B667B2E429FA9519C02D485968818C1C77E3100D747C5E609B0154
[15063] 1612941480.177418: Preauth module encrypted_timestamp (2) (real) returned: 0/Success
[15063] 1612941480.177419: Produced preauth for next request: PA-ENC-TIMESTAMP (2)
[15063] 1612941480.177420: Sending request (269 bytes) to DOMAIN.LOCAL
[15063] 1612941480.177421: Sending initial UDP request to dgram 192.168.88.99:88
[15063] 1612941480.177422: Received answer (96 bytes) from dgram 192.168.88.99:88
[15063] 1612941480.177423: Response was from master KDC
[15063] 1612941480.177424: Received error from KDC: -1765328332/Response too big for UDP, retry with TCP
[15063] 1612941480.177425: Request or response is too big for UDP; retrying with TCP
[15063] 1612941480.177426: Sending request (269 bytes) to DOMAIN.LOCAL (tcp only)
[15063] 1612941480.177427: Initiating TCP connection to stream 192.168.88.99:88
[15063] 1612941480.177428: Sending TCP request to stream 192.168.88.99:88
[15063] 1612941480.177429: Received answer (1510 bytes) from stream 192.168.88.99:88
[15063] 1612941480.177430: Terminating TCP connection to stream 192.168.88.99:88
[15063] 1612941480.177431: Response was from master KDC
[15063] 1612941480.177432: Processing preauth types: PA-ETYPE-INFO2 (19)
[15063] 1612941480.177433: Selected etype info: etype aes256-cts, salt "DOMAIN.LOCALhostubuntu20.domain.local", params ""
[15063] 1612941480.177434: Produced preauth for next request: (empty)
[15063] 1612941480.177435: AS key determined by preauth: aes256-cts/9559
[15063] 1612941480.177436: Decrypted AS reply; session key is: aes256-cts/38BB
[15063] 1612941480.177437: FAST negotiation: unavailable
[15063] 1612941480.177438: Initializing FILE:/tmp/tmpfqfk2yi9 with default princ UBUNTU20$@DOMAIN.LOCAL
[15063] 1612941480.177439: Storing UBUNTU20$@DOMAIN.LOCAL -> krbtgt/DOMAIN.LOCAL@DOMAIN.LOCAL in FILE:/tmp/tmpfqfk2yi9
[15063] 1612941480.177440: Storing config in FILE:/tmp/tmpfqfk2yi9 for krbtgt/DOMAIN.LOCAL@DOMAIN.LOCAL: pa_type: 2
[15063] 1612941480.177441: Storing UBUNTU20$@DOMAIN.LOCAL -> krb5_ccache_conf_data/pa_type/krbtgt\/DOMAIN.LOCAL\@DOMAIN.LOCAL@X-CACHECONF: in FILE:/tmp/tmpfqfk2yi9
Using Kerberos credential cache /tmp/tmpfqfk2yi9
[15017] 1612941480.217226: ccselect module realm chose cache FILE:/tmp/tmpfqfk2yi9 with client principal UBUNTU20$@DOMAIN.LOCAL for server principal ldap/192.168.88.99@DOMAIN.LOCAL
[15017] 1612941480.217227: Getting credentials UBUNTU20$@DOMAIN.LOCAL -> ldap/192.168.88.99@ using ccache FILE:/tmp/tmpfqfk2yi9
[15017] 1612941480.217228: Retrieving UBUNTU20$@DOMAIN.LOCAL -> ldap/192.168.88.99@ from FILE:/tmp/tmpfqfk2yi9 with result: -1765328243/Matching credential not found (filename: /tmp/tmpfqfk2yi9)
[15017] 1612941480.217229: Retrying UBUNTU20$@DOMAIN.LOCAL -> ldap/192.168.88.99@DOMAIN.LOCAL with result: -1765328243/Matching credential not found (filename: /tmp/tmpfqfk2yi9)
[15017] 1612941480.217230: Server has referral realm; starting with ldap/192.168.88.99@DOMAIN.LOCAL
[15017] 1612941480.217231: Retrieving UBUNTU20$@DOMAIN.LOCAL -> krbtgt/DOMAIN.LOCAL@DOMAIN.LOCAL from FILE:/tmp/tmpfqfk2yi9 with result: 0/Success
[15017] 1612941480.217232: Starting with TGT for client realm: UBUNTU20$@DOMAIN.LOCAL -> krbtgt/DOMAIN.LOCAL@DOMAIN.LOCAL
[15017] 1612941480.217233: Requesting tickets for ldap/192.168.88.99@DOMAIN.LOCAL, referrals on
[15017] 1612941480.217234: Generated subkey for TGS request: aes256-cts/3C4C
[15017] 1612941480.217235: etypes requested in TGS request: aes256-cts, aes128-cts, aes256-sha2, aes128-sha2, des3-cbc-sha1, rc4-hmac, camellia128-cts, camellia256-cts
[15017] 1612941480.217237: Encoding request body and padata into FAST request
[15017] 1612941480.217238: Sending request (1653 bytes) to DOMAIN.LOCAL
[15017] 1612941480.217239: Initiating TCP connection to stream 192.168.88.99:88
[15017] 1612941480.217240: Sending TCP request to stream 192.168.88.99:88
[15017] 1612941480.217241: Received answer (319 bytes) from stream 192.168.88.99:88
[15017] 1612941480.217242: Terminating TCP connection to stream 192.168.88.99:88
[15017] 1612941480.217243: Response was from master KDC
[15017] 1612941480.217244: Decoding FAST response
[15017] 1612941480.217245: TGS request result: -1765328377/Server not found in Kerberos database
[15017] 1612941480.217246: Requesting tickets for ldap/192.168.88.99@DOMAIN.LOCAL, referrals off
[15017] 1612941480.217247: Generated subkey for TGS request: aes256-cts/D031
[15017] 1612941480.217248: etypes requested in TGS request: aes256-cts, aes128-cts, aes256-sha2, aes128-sha2, des3-cbc-sha1, rc4-hmac, camellia128-cts, camellia256-cts
[15017] 1612941480.217250: Encoding request body and padata into FAST request
[15017] 1612941480.217251: Sending request (1653 bytes) to DOMAIN.LOCAL
[15017] 1612941480.217252: Initiating TCP connection to stream 192.168.88.99:88
[15017] 1612941480.217253: Sending TCP request to stream 192.168.88.99:88
[15017] 1612941480.217254: Received answer (319 bytes) from stream 192.168.88.99:88
[15017] 1612941480.217255: Terminating TCP connection to stream 192.168.88.99:88
[15017] 1612941480.217256: Response was from master KDC
[15017] 1612941480.217257: Decoding FAST response
[15017] 1612941480.217258: TGS request result: -1765328377/Server not found in Kerberos database
Traceback (most recent call last):
  File "/root/lukscrow/./lukscrow", line 222, in <module>
    main()
  File "/root/lukscrow/./lukscrow", line 196, in main
    con = connect_ad(args.ldap_url)
  File "/root/lukscrow/./lukscrow", line 71, in connect_ad
    con.sasl_interactive_bind_s('', auth_tokens)
  File "/root/.pyenv/versions/3.9.1/envs/lukscrow-env/lib/python3.9/site-packages/ldap/ldapobject.py", line 476, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_flags)
  File "/root/.pyenv/versions/3.9.1/envs/lukscrow-env/lib/python3.9/site-packages/ldap/ldapobject.py", line 340, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/root/.pyenv/versions/3.9.1/envs/lukscrow-env/lib/python3.9/site-packages/ldap/compat.py", line 46, in reraise
    raise exc_value
  File "/root/.pyenv/versions/3.9.1/envs/lukscrow-env/lib/python3.9/site-packages/ldap/ldapobject.py", line 324, in _ldap_call
    result = func(*args,**kwargs)
ldap.LOCAL_ERROR: {'result': -2, 'desc': 'Local error', 'ctrls': [], 'info': 'SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database)'}
```

**Comment by ambalabanov** [comment]
Solved by configuring a reverse lookup zone containing pointer (PTR) records for your domain in Active Directory DNS.
